jenkins:
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  clouds:
    - kubernetes:
        containerCap: 10
        containerCapStr: "10"
        jenkinsTunnel: "jenkins-agent:50000"
        jenkinsUrl: "http://172.18.0.100"
        maxRequestsPerHost: 32
        maxRequestsPerHostStr: "32"
        name: "kubernetes"
        namespace: "jenkins"  # Jenkins 네임스페이스로 설정
        podLabels:
          - key: "jenkins/jenkins-jenkins-slave"
            value: "true"
        serverUrl: "https://kubernetes.default"
        templates:
          - name: "default"
            label: "jenkins-jenkins-slave"
            serviceAccount: "jenkins"
            nodeUsageMode: NORMAL
            podRetention: "never"
            hostNetwork: false
            yamlMergeStrategy: "override"
            # 권한 설정을 위한 securityContext 추가
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
            containers:
              - name: "jnlp"
                image: "jenkinsci/docker-inbound-agent:latest"  # Docker가 포함된 에이전트 이미지
                workingDir: "/home/jenkins"
                command:
                  - "sh"
                  - "-c"
                  - |
                    # docker 그룹의 GID를 호스트와 맞추고 jenkins 사용자를 추가
                    DOCKER_GID=$(stat -c '%g' /var/run/docker.sock) && \
                    groupadd -for -g ${DOCKER_GID} docker && \
                    usermod -aG docker jenkins && \
                    # Jenkins 에이전트 실행
                    exec /usr/local/bin/jenkins-agent
                args: "${computer.jnlpmac} ${computer.name}"
                envVars:
                  - envVar:
                      key: "JENKINS_URL"
                      value: "http://172.18.0.100"
                resourceLimitCpu: "512m"
                resourceLimitMemory: "512Mi"
                resourceRequestCpu: "512m"
                resourceRequestMemory: "512Mi"
                volumeMounts:
                  - name: "docker-sock"
                    mountPath: "/var/run/docker.sock"
                  - name: "kubectl"
                    mountPath: "/usr/bin/kubectl"
                  # 필요한 경우 에이전트 파드에 PVC 마운트 추가
                  - name: "jenkins-pvc"
                    mountPath: "/home/jenkins"
            volumes:
              - name: "docker-sock"
                hostPath:
                  path: "/var/run/docker.sock"
              - name: "kubectl"
                hostPath:
                  path: "/usr/local/bin/kubectl"
              # 에이전트 파드에 PVC 마운트를 위한 볼륨 정의
              - name: "jenkins-pvc"
                persistentVolumeClaim:
                  claimName: "jenkins"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  disableRememberMe: false
  disabledAdministrativeMonitors:
    - "hudson.model.UpdateCenter$CoreUpdateMonitor"
    - "jenkins.diagnostics.RootUrlNotSetMonitor"
    - "jenkins.security.UpdateSiteWarningsMonitor"
  labelAtoms:
    - name: "master"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 2  # 노드의 executors 수 설정
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm: "legacy"
  slaveAgentPort: 50000
  updateCenter:
    sites:
      - id: "default"
        url: "https://raw.githubusercontent.com/IaC-Source/Jenkins-updateCenter/main/update-center.json"
  views:
    - all:
        name: "all"
  viewsTabBar: "standard"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  sSHD:
    port: -1
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitSCM:
    createAccountBasedOnEmail: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
tool:
  git:
    installations:
      - home: "git"
        name: "Default"
